# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application-prod.yml file.
# ===================================================================

spring:
  profiles: prod
server:
    port: 8080